### ISSUE TITLE
AdminApp: Categories

### ISSUE THREAD

**Issue by adyplin** [EC-rika-project/AdminApp-RIKA-WIN23#13]
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#31

- [ ] EC-rika-project/AdminApp-RIKA-WIN23#32

- [ ] EC-rika-project/AdminApp-RIKA-WIN23#33

- [ ] EC-rika-project/AdminApp-RIKA-WIN23#34

- [ ] EC-rika-project/AdminApp-RIKA-WIN23#35
