### ISSUE TITLE
AdminApp: Orders

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#14]
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#37
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#38
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#39
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#40
