### ISSUE TITLE
AdminApp: Products

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#15]
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#41
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#45
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#47
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#46
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#48
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#43
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#42
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#49
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#24
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#26
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#28
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#30
