### ISSUE TITLE
AdminApp: Users

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#16]
- [ ] EC-rika-project/dummie-repo#145
- [ ] EC-rika-project/dummie-repo#146
- [ ] EC-rika-project/dummie-repo#147
- [ ] EC-rika-project/dummie-repo#148
- [ ] EC-rika-project/dummie-repo#149
- [ ] EC-rika-project/dummie-repo#150
- [ ] EC-rika-project/dummie-repo#151
![Image](https://github.com/user-attachments/assets/bc9d349c-94b9-415b-b15f-24364684cec3)
