### ISSUE TITLE
Uppsättning AdminApp

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#17]
**Tasks:**
- [x]  Skapa GitHub-repo
- [x]  Sätt upp projekt inklusive mappstruktur
- [x] Skapa main branch
- [x] Skapa dev branch
