### ISSUE TITLE
AdminApp-Products: Som en admin vill jag kunna skapa en ny produktgrupp.

### ISSUE THREAD

**Issue by FredrikssonAndreas** [EC-rika-project/AdminApp-RIKA-WIN23#24]
**Task:**
- [ ] AdminApp-Products: CREATE - Skriv en funktion för att kunna skapa en ny produktgrupp med följande entiteter. (exempelvis)
[ ] Produktgrupps namn (productGroup)
[ ] Produkt variation (productVariation)

- [ ] Implementera validering som gör att fält inte kan vara tomma.
- [ ] När produktgrupp är skapad ska data skickas vidare och sparas i databasen. 
     - Vid success "200" productApi returnerar ProductGroupId.
     - Vid fail  ex "400" ev. felmeddelande.

**Definition of done:**

- [ ] Alla obligatoriska fält är populerade (produktgrupps namn, produkt variation).
- [ ]  Produktgrupp sparas korrekt i databasen med all tillhörande information.
- [ ] Validering finns om ett fält är tomt.
- [ ]  Felmeddelanden visas tydligt för admin vid felaktiga inmatningar.
- [ ]  En användarvänlig bekräftelse visas när produktgruppen skapats framgångsrikt.
- [ ]  Produktgruppen kan hämtas och visas korrekt i en lista över produktgrupper efter att den har skapats.
- [ ] Att efter lyckat skapande skickas data vidare till databasen
