### ISSUE TITLE
AdminApp-Products: Som en admin vill jag kunna hämta en eller flera produktgrupper.

### ISSUE THREAD

**Issue by FredrikssonAndreas** [EC-rika-project/AdminApp-RIKA-WIN23#26]
**Task:**
- [ ] AdminApp-Products: Skapa en funktion som hämtar en produktgrupp med hjälp av productGroupId.
- [ ] AdminApp-Products: Informationen som returneras ska innehålla (kategori, produkter, variationer)
- [ ] AdminApp-Products: Skapa en funktion som hämtar alla produktgrupper i en katergori med hjälp av categoryId.
- [ ] AdminApp-Products: Skapa en funktion som hämtar alla produktgrupper med hjälp av GetAllProductGroups();
- [ ] AdminApp-Products: Implementera API-kall för att hämta ut flera / alla produktergrupper från databasen.
- [ ] AdminApp-Products: Implementera API-kall för att hämta en produktgrupp från databasen.
- [ ] AdminApp-Products: Hantera fall där produktgruppen inte existerar, och returnera lämpliga felmeddelanden.

**Definition of done**
- [ ] Administratören ska kunna hämta en produktgrupp genom att ange produktgruppens ID.
- [ ] Systemet ska validera om produkten med det angivna ID:et existerar i databasen och alltid returnera en statuskod beroende på resultatet.
- [ ] Den returnerade produkten ska inkludera relaterad information, såsom produkter om dessa relationer finns.
- [ ] Administratören ska kunna hämta ut flera produktgrupper genom att ange produktengruppens kategori ID.
- [ ] Administratören ska kunna hämta ut alla produktgrupper genom GetAllProductGroups();
