### ISSUE TITLE
AdminApp-Products: Som en admin vill jag kunna uppdatera en produktgrupp.

### ISSUE THREAD

**Issue by FredrikssonAndreas** [EC-rika-project/AdminApp-RIKA-WIN23#28]
**Task:**
- [ ] AdminApp-Products: Skriv en funktion som kan uppdatera en produktgrupp med hjälp av productGroupId.
- [ ] AdminApp-Products: Informationen som returneras och kunna uppdateras ska innehålla, 
  [ ] Produktgrupps namn (productGroup)
  [ ] Produkt variation (productVariation)
- [ ] AdminApp-Products: Validera data för redigering (t.ex. om produktgruppen existerar och om fält är giltiga)
- [ ] AdminApp-Products: Implementera API-kall för att hämta en produktgrupp från databasen.
- [ ] AdminApp-Products: När produktgrupp är redigerad ska data skickas vidare och sparas i databasen.

**Defintion of done:**
- [ ] Admin kan uppdatera en produktgrupp med hjälp av produktgruppens ID.
- [ ] Admin ska kunna redigera en produktgrupp genom att ange produktgruppens ID och de fält som ska uppdateras, som till exempel namn, beskrivning.
- [ ] Systemet ska validera om produktgruppen med det angivna ID:et existerar i databasen och så att alla obligatoriska fält är ifyllda. API:et ska alltid returnera en statuskod beroende på resultatet.
- [ ] Om valideringen lyckas, ska systemet uppdatera fälten som är redigerade.
