### ISSUE TITLE
AdminApp-Products: Som en admin vill jag kunna ta bort en produktgrupp.

### ISSUE THREAD

**Issue by adyplin** [EC-rika-project/AdminApp-RIKA-WIN23#30]
**Task:**

- [ ] AdminApp-Products: Skriv en funktion som kan ta bort en produktgrupp med hjälp av productGroupId.
- [ ] AdminApp-Products: Gör ett API-kall för att skicka en begäran till databasen för att ta bort en produktgrupp.

- [ ] Lägg till bekräftelse / felmeddelande
-  Vid success "200" visa bekräftelsemeddelande
-  Vid error ex "400" ev. felmeddelande.

**Defintion of done:**
- [ ] Admin kan ta bort en produktgrupp med hjälp av produktgruppens ID 
- [ ] En användarvänlig bekräftelse visas när produktgruppen tagits bort framgångsrikt.
- [ ] Ett felmeddelande visas när man misslyckats med borttagning av produktgruppen.
