### ISSUE TITLE
AdminApp-Categories: Som admin vill jag kunna skapa nya kategorier.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#31]
**Task:**
- [ ] AdminApp-Categories: CREATE - Skriv en funktion för att kunna skapa nya kategorier med följande entiteter. (exempelvis)
  [ ] Kategorinamn (categoryName)

- [ ] Implementera validering som gör att fält inte kan vara tomma.
- [ ] När en kategori är skapad ska data skickas vidare och sparas i databasen EC-rika-project/API-Products-RIKA-WIN23#23 

**Definition of done:**

- [ ] Alla obligatoriska fält är populerade (categoryName).
- [ ]  Kategorier sparas korrekt i databasen med all tillhörande information.
- [ ] Validering finns om ett fält är tomt.
- [ ]  Felmeddelanden visas tydligt för admin vid felaktiga inmatningar.
- [ ]  En användarvänlig bekräftelse visas när kategorien skapats framgångsrikt.
- [ ]  Kategorin kan hämtas och visas korrekt i kategorilistan efter att den har skapats.
- [ ] Att efter lyckat skapande skickas data vidare till databasen
