### ISSUE TITLE
AdminApp-Categories: Som admin vill jag kunna  uppdatera en kategori.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#33]
**Tasks:**

- [ ] AdminApp-Orders: Skriv en funktion som kan uppdatera en kategori med hjälp av categoryId -> UpdateOneByCategoryId();

- [ ] AdminApp-Orders: Implementera API-kall för att uppdatera en kategori från EC-rika-project/API-Products-RIKA-WIN23#23 

**Defintion of Done:**

- [ ] Admin kan uppdatera en kategori med hjälp av kategori Id.

- [ ] API-kall för att uppdatera och spara en kategori.
