### ISSUE TITLE
AdminApp-Categories: Som admin vill jag kunna ta bort en kategori.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#34]
**Tasks:**

- [ ] AdminApp-Categories: Skriv en funktion som kan ta bort en kategori med hjälp av categoryId DeleteOne(categoryId).

- [ ] AdminApp-Categories: Gör ett API-kall för att skicka en begäran till databasen för att ta bort en kategori EC-rika-project/API-Products-RIKA-WIN23#23 

**Defintion of Done:**

- [ ] Admin kan ta bort en kategori med hjälp av categoryId.
- [ ] Se till att kategori tas bort i API
