### ISSUE TITLE
AdminApp-Orders: Som admin vill jag kunna skapa en ny order.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#36]
**Task:**
- [ ] AdminApp-Orders: CREATE - Skriv en funktion för att kunna skapa nya ordrar med följande entiteter. (exempelvis)
  [ ] Artikelnummer (articleNumber)
  [ ] Kund (userId)

- [ ] Implementera validering som gör att fält inte kan vara tomma.
- [ ] När order är skapad ska data skickas vidare och sparas i databasen EC-rika-project/API-Orders-RIKA-WIN23#1  

**Definition of done:**

- [ ]  Alla obligatoriska fält är populerade (artikelnummer, userId).
- [ ]  Orders sparas korrekt i databasen med all tillhörande information.
- [ ]  Validering finns om ett fält är tomt.
- [ ]  Felmeddelanden visas tydligt för admin vid felaktiga inmatningar.
- [ ]  En användarvänlig bekräftelse visas när ordern skapats framgångsrikt.
- [ ]  Ordern kan hämtas och visas korrekt i orderlistan efter att den har skapats.
- [ ]  Efter lyckat skapande av order skickas data vidare till databasen
