### ISSUE TITLE
AdminApp-Orders: Som admin vill jag kunna uppdatera en eller flera ordrar.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#38]
**Tasks:**

- [ ] AdminApp-Orders: Skriv en funktion som kan uppdatera en order med hjälp av ordernummer UpdateOne(orderId).

- [ ] AdminApp-Orders: Implementera API-kall för att uppdatera en order från EC-rika-project/API-Orders-RIKA-WIN23#1 

**Defintion of Done:**

- [ ] Admin kan uppdatera en order med hjälp av ordernummer.

- [ ] API-kall för att uppdatera och spara en order.
