### ISSUE TITLE
AdminApp-Orders: Som admin vill jag kunna ta bort en eller flera ordrar.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#39]
**Tasks:**

- [ ] AdminApp-Orders: Skriv en funktion som kan ta bort en order med hjälp av ordernummer DeleteOne(orderId).

- [ ] AdminApp-Orders: Gör ett API-kall för att skicka en begäran till databasen för att ta bort en order EC-rika-project/API-Orders-RIKA-WIN23#1

**Defintion of Done:**

- [ ] Admin kan ta bort en order med hjälp av ordernummer.
- [ ] Se till att order tas bort i API
