### ISSUE TITLE
AdminApp-Products: Som en admin vill jag kunna skapa en ny produkt.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#41]
**Task:**
- [ ] AdminApp-Products: CREATE - Skriv en funktion för att kunna skapa nya produkter med följande entiteter. (exempelvis)
[ ] Produktnamn (productName)
[ ] Pris (price)
[ ] Reapris (discountPrice)
[ ] Beskrivning (ingress)
[ ] Bild (imgUrl)
[ ] Kategori (category)
[ ] Produktgrupp (productGroup)
   [ ] Produkt variation (productVariation)
[ ] Artikelnummer (articleNumber)
[ ] Storlek (size)
[ ] Färg (color)

- [ ] Implementera validering som gör att fält inte kan vara tomma.
- [ ] När produkt är skapad ska data skickas vidare och sparas i databasen.
     - Vid success "200" productApi returnerar ProductId.
     - Vid fail  ex "400" ev. felmeddelande.

**Definition of done:**

- [ ] Alla obligatoriska fält är populerade (produktnamn, pris, kategori, artikelnummer, storlek, färg).
- [ ]  Produkter sparas korrekt i databasen med all tillhörande information.
- [ ] Validering finns om ett fält är tomt.
- [ ]  Felmeddelanden visas tydligt för admin vid felaktiga inmatningar.
- [ ]  En användarvänlig bekräftelse visas när produkten skapats framgångsrikt.
- [ ]  Produkten kan hämtas och visas korrekt i produktlistan efter att den har skapats.
- [ ] Att efter lyckat skapande skickas data vidare till databasen 

**Aktivtetsdiagram**

![Image](https://github.com/user-attachments/assets/408be026-4fb0-42cb-a261-8c6315e3979b)
