### ISSUE TITLE
AdminApp-Products:  Som en admin vill jag ha funktionalitet för att hantera priser.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#42]
**Task:**
- [ ] AdminApp-Products: funktionalitet för att kunna sätta ett nypris (price).
- [ ] AdminApp-Products: funktionalitet för att kunna ändra till ett reapris (discountPrice).

**Definition of Done:** 

- [ ] När funktionalitet för att ändra pris finns. 
- [ ] När funktionalitet för att addera ett reapris finns.
