### ISSUE TITLE
AdminApp-Products: Som en admin vill jag ha funktionalitet för att hantera lagersaldo. 

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#43]
**Task:**
- [ ] AdminApp-Products: Det ska finnas en funktion för att manuellt kunna ändra lagersaldot.
- [ ] AdminApp-Products: Ska finnas val för varför lagersaldot ändras manuellt (inventering vid  plock, skadade produkter, internt bruk osv) för dokumentation. 

**Definition of Done:**

- [ ] När det finns funktionalitet för att kunna ändra lagersaldo på produkten. 
- [ ] Man ska kunna lägga till en notering till varför lagersaldot ändras manuellt. 
- [ ]  Ett bekräftelsemeddelande visas när lagersaldot har uppdaterats framgångsrikt.
- [ ]  Lagersaldot sparas korrekt i databasen och uppdateras i produktlistan.
- [ ] Systemet visar tydliga felmeddelanden om admin försöker uppdatera lagersaldot med ogiltiga värden (t.ex. negativt tal, ej numeriskt värde).

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/ad2a941e-ab85-44fa-ad97-dd577148b87c)
