### ISSUE TITLE
AdminApp-Users: Som admin vill jag ha en enkel men snygg och användarvänlig design för att hantera formuläret och användarna.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#44]
**Task:**
- [ ] AdminApp-Users: CREATE - Skapa ett formulär där admins kan lägga till nya användare med alla nödvändiga fält - 
[ ] Roll
[ ] Användarnamn 
[ ] E-post
[ ] Lösenord
- [ ] AdminApp-Users: CREATE - Skapa en select meny för att kunna välja olika roller.
- [ ] AdminApp-Users: READ - Skapa en tabell för att kunna hämta ut användare.
[ ] Roll
[ ] Användarnamn 
[ ] E-post
[ ] Orderhistorik
- [ ] AdminApp-Users: READ - Skapa en select meny för att filtrera användare baserat på roll.
- [ ] AdminApp-Users: UPDATE - Lägg till en knapp på tabellen för att kunna uppdatera användare.
- [ ] AdminApp-Users: DELETE - Lägg till en knapp på tabellen för att kunna ta bort användare.
- [ ] AdminApp-Users: DELETE - Implementera en bekräftelsedialog ("Är du säker?") innan en användare tas bort.
- [ ] AdminApp-Users: Skapa en knapp för att kunna spara all information

**Definition of done:**

**Formulär för att lägga till användare populerat med följande fält:**
- [ ] En select meny finns för att välja roller
- [ ] Ett formulär är implementerat för att skapa användare som inkluderar fält för:
[ ] Roll 
[ ] Användarnamn 
[ ] E-post 
 [ ] Lösenord 

**Användartabell för att lista upp användare finns:**

- [ ]  En tabell har skapats för att visa listan över användare, med följande fält:
 [ ] Roll
 [ ] Användarnamn
 [ ] E-post
[ ] Orderhistorik

**Valmeny för att filtrera användare:**

- [ ] En select meny finns för att filtrera användare baserat på deras roll.

**Generellfunktionalitet:**
- [ ]  Samtliga fält valideras
- [ ] En knapp för att spara information och skicka in formuläret finns
- [ ] En uppdateringsknapp läggs till för varje användare i tabellen.
- [ ] En borttagningsknapp läggs till för varje användare i tabellen.
