### ISSUE TITLE
AdminApp-Products:  Som en admin vill jag kunna ta bort en eller flera produkter.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#46]
**Tasks:**

- [ ] AdminApp-Products: Skriv en funktion som kan ta bort en produkt med hjälp av productId.
- [ ] AdminApp-Products: Skriv en funktion som kan ta bort en produkt med hjälp av produktnamn.
- [ ] AdminApp-Products: Gör ett API-kall för att skicka en begäran till databasen för att ta bort en eller flera produkter EC-rika-project/API-Products-RIKA-WIN23#23 

- [ ] Lägg till bekräftelse / felmeddelande
-  Vid success "200" visa bekräftelsemeddelande
-  Vid error ex "400" ev. felmeddelande.

**Defintion of Done:**

- [ ] Admin kan ta bort en produkt med hjälp av productId eller produktnamn.
- [ ] Visa meddelande vid misslyckande av borttagning och likväl ett meddelande för lyckad borttagning av produkt.

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/2e0e4877-d178-4315-b238-0a24e3e92730)
