### ISSUE TITLE
AdminApp-Products: Som en admin vill jag kunna uppdatera en produkt.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#47]
**Tasks:**

- [ ] AdminApp-Products: Skriv en funktion som kan uppdatera en produkt med hjälp av productId.
- [ ] AdminApp-Products: Skriv en funktion som kan uppdatera en produkt med hjälp av produktnamn.
- [ ] AdminApp-Products: Informationen som returneras ska innehålla,
  [ ] Produktnamn (productName)
  [ ] Pris (price)
  [ ] Reapris (discountPrice)
  [ ] Beskrivning (ingress)
  [ ] Bild (imgUrl)
  [ ] Kategori (category)
  [ ] Produktgrupp (productGroup)
  [ ] Produkt variation (productVariation)
  [ ] Artikelnummer (articleNumber)
  [ ] Storlek (size)
  [ ] Färg (color)

- [ ] AdminApp-Products: Implementera API-kall för att hämta en produkt från EC-rika-project/API-Products-RIKA-WIN23#23 
- [ ] AdminApp-Products: Implementera API-kall för att hämta ut flera produkter från EC-rika-project/API-Products-RIKA-WIN23#23

**Defintion of Done:**

- [ ] Admin kan uppdatera en produkt med hjälp av artikelnummer eller produktnamn.

- [ ] Informationen som ska uppdateras innehåller,
  [ ] Produktnamn (productName)
  [ ] Pris (price)
  [ ] reapris (discountPrice)
  [ ] Beskrivning (ingress)
  [ ] Bild (imgUrl)
  [ ] Kategori (category)
  [ ] Produktgrupp (productGroup)
  [ ] Produkt variation (productVariation)
  [ ] Artikelnummer (articleNumber)
  [ ] Storlek (size)
  [ ] Färg (color)

- [ ] API-kall för att uppdatera och spara en produkt är implementerade.

**Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/1ea0f305-6ddc-4219-b670-a79dd79a91e0)
