### ISSUE TITLE
AdminApp-Users: Som admin vill jag kunna hantera och sätta olika roller på användare.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#50]
**Tasks:**
- [ ] AdminApp-Users: Det ska finnas en admin roll (Som kan hantera känslig data).
- [ ] AdminApp-Users: Det ska finnas en member roll (Som användare på WebApp får automatiskt vid skapande av konto)

**Definition of Done:**
- [ ] När de bestämda rollerna finns i databasen. 
- [ ] När finns funktionalitet att hantera roller. 

**Aktivitets diagram**
![Image](https://github.com/user-attachments/assets/d6605bc7-1eae-4107-9304-bbbd9025e655)
