### ISSUE TITLE
AdminApp-Users: Som admin vill jag att standard beteende är att användare får rollen "member" när man skapar ett konto.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#51]
**Tasks:**
- [ ] AdminApp-Users: Som användare på WebApp ska man automatiskt vid skapande av konto få rollen member.
- [ ] AdminApp-Users: Member rollen ska med en funktion hämtas från EC-rika-project/API-Users-RIKA-WIN23#2 och tilldeles till den nya användaren.

**Definition of Done:**
- [ ] När det går att hämta ut rollen från Api och tilldela detta till en ny användare.

**Aktivitets diagram**
![Image](https://github.com/user-attachments/assets/c86a019b-8775-46a5-9e61-343ca3854d1c)
