### ISSUE TITLE
AdminApp-Users: Som admin vill jag kunna skapa en användare.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#52]
**Task:**
- [ ]  AdminApp-Users: Det ska finnas funktionalitet för att kunna skapa nya användare som admin.
[ ] Användarnamn 
[ ] Roll
[ ] Email
[ ] Lösenord

- [ ] AdminApp-Users: Användarnamnet måste vara unikt och inte redan finnas registrerat.
- [ ] AdminApp-Users: Validering av användarnamn(regex, min 2 tecken).
- [ ] AdminApp-Users: Tempdata ska finnas om användarnamn är giltigt eller ogiltigt.
- [ ] AdminApp-Users: Email adress måste vara unik och inte redan finnas registrerat.
- [ ] AdminApp-Users: Validering av email ska finnas (regex)
- [ ] AdminApp-Users: Tempdata ska finnas om email adress är giltigt eller ogiltigt.
- [ ] AdminApp-Users: Validering lösenord ska finnas (regex, minst en stor bokstav, en liten bokstav, en siffra och ett tecken)
- [ ] AdminApp-Users: Tempdata ska finnas för om lösenord är giltigt eller ogiltigt

- [ ] AdminApp-Users: Vid lyckat skapande av en ny användare ska data skickas vidare till EC-rika-project/API-Users-RIKA-WIN23#2 

**Definition of Done:**

- [ ]  När funktionalitet för att skapa nya användare finns.
- [ ] Att efter lyckat skapande skickas data vidare till databasen Api:Users
- [ ] När validering funkar med javascript.
- [ ] Felhantering är implementerad: Om data inte kan skickas vidare, visas ett tydligt felmeddelande och processen loggas.

**Aktivitets diagram**
![Image](https://github.com/user-attachments/assets/820f88b7-1313-4b1c-99f8-e703f58b37b6)
