### ISSUE TITLE
AdminApp-Users: Som admin vill jag kunna hämta ut information om en eller flera användare.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#53]
**Tasks:**
- [ ] AdminApp-Users: Skriv en funktion som hämtar en användare med hjälp av ID.
- [ ] AdminApp-Users: Skriv en funktion som hämtar en användare med hjälp av email.
- [ ] AdminApp-Users: Skriv en funktion så att admin kan hämta ut flera användare i en lista.
- [ ] AdminApp-Users: Informationen som returneras ska innehålla namn, e-post, roller, orderhistorik.
- [ ] AdminApp-Users: Implementera API-kall för att hämta en användare från EC-rika-project/API-Users-RIKA-WIN23#2 
- [ ] AdminApp-Users: Implementera API-kall för att hämta ut flera användare från EC-rika-project/API-Users-RIKA-WIN23#2 

**Defintion of Done:** 
- [ ] Admin kan hämta en användare med hjälp av ID eller e-post.
- [ ] Admin kan hämta flera användare i en lista.
- [ ] Informationen som returneras innehåller namn, e-post, roller, och orderhistorik.
- [ ] Funktionerna har täckande enhetstester som verifierar korrekt funktionalitet.
- [ ] API-kall för att hämta en eller flera användare är implementerade.

**Aktivitets diagram**
![Image](https://github.com/user-attachments/assets/3d71edc1-8461-449d-9f56-c6c25c997516)
