### ISSUE TITLE
AdminApp-Users: Som admin vill jag  kunna uppdatera information om en användare.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#54]
**Tasks:**
- [ ] AdminApp-Users: Skriv en funktion som gör det möjligt att uppdatera en användares information.
- [ ] AdminApp-Users: Skriv en funktion som validerar den uppdaterade informationen (t.ex. korrekt e-postformat, giltiga roller).
- [ ] AdminApp-Users: Säkerställ att all obligatorisk användardata finns innan uppdatering sker.
- [ ] AdminApp-Users: Implementera API-kall för att skicka den uppdaterade informationen till servern/databasen EC-rika-project/API-Users-RIKA-WIN23#2 
- [ ] AdminApp-Users: Testa att felmeddelanden visas korrekt om uppdateringen misslyckas (t.ex. vid felaktiga fält).

**Definition of Done:** 
- [ ] När det finns funktionalitet för att ändra eller uppdatera en användares information. 
- [ ] Admin kan uppdatera en användares information (t.ex. namn, e-post, roll).
- [ ]  All data valideras innan uppdateringen sparas.
- [ ]  Felmeddelanden visas om uppdateringen misslyckas, med detaljer om vad som gick fel.

**Aktivitets diagram**

![Image](https://github.com/user-attachments/assets/f964f782-390c-44f0-a44c-5dda1a2bd949)
