### ISSUE TITLE
AdminApp-Users: Som admin vill jag  kunna ta bort en eller flera användare.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#55]
**Task:**
- [ ] AdminApp-Users: Skriv en funktion som gör det möjligt att ta bort en användare baserat på användarens ID.
- [ ] AdminApp-Users: Skriv en funktion som möjliggör att välja och ta bort flera användare samtidigt.
- [ ] AdminApp-Users: Gör ett API-kall för att skicka en begäran till databasen för att ta bort en eller flera användare EC-rika-project/API-Users-RIKA-WIN23#2 
- [ ] AdminApp-Users: Tvåstegsverifiering för att säkerställa om man verkligen vill ta bort en användare.

**Defintion of Done:**

- [ ] Admin kan ta bort en eller flera användare från systemet baserat på deras ID.
- [ ]  En bekräftelsedialog visas innan borttagning genomförs, både för enskilda och flera användare.

**Aktivitets diagram**
![Image](https://github.com/user-attachments/assets/46f667a4-31e6-4467-9c80-e7310eb5d08d)
