### ISSUE TITLE
AdminApp: Users

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#56]
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#50
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#51
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#52
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#53
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#54
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#55
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#44
![Image](https://github.com/user-attachments/assets/bc9d349c-94b9-415b-b15f-24364684cec3)
