### ISSUE TITLE
AdminApp-Products: Som en admin vill jag kunna hämta flera produktgrupper

### ISSUE THREAD

**Issue by adyplin** [EC-rika-project/AdminApp-RIKA-WIN23#57]
**Task:**
- [ ] AdminApp-Products: Skapa en funktion som hämtar alla produktgrupper i en katergori med hjälp av categoryId.
- [ ] AdminApp-Products: Skapa en funktion som hämtar alla produktgrupper med hjälp av GetAllProductGroups();
- [ ] AdminApp-Products: Implementera API-kall för att hämta ut flera / alla produktergrupper från databasen.

**Definition of done**
- [ ] Administratören ska kunna hämta ut flera produktgrupper genom att ange produktengruppens kategori ID.
- [ ] Administratören ska kunna hämta ut alla produktgrupper genom GetAllProductGroups();
