### ISSUE TITLE
AdminApp: Home

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/AdminApp-RIKA-WIN23#7]
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#8
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#9
- [ ] EC-rika-project/AdminApp-RIKA-WIN23#10
